- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  color: "#FFD700"
  playTimeTracker: JobCaptain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 172800 #48 hrs   
    - !type:RoleTimeRequirement
      role: JobHeadOfPersonnel
      time: 43200 #12 hours
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 21600 #6 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 86400 #24 hours
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter
